# Generated by Django 5.2.5 on 2025-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_order_driver_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='driver_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
